smtp:
  from: noreply@kevindev.com.br
  to: kevinmg50@gmail.com
  host: smtp.hostinger.com
  port: 587

webhooks:
  discord: https://discord.com/api/webhooks/1103840164062707762/hmu05z5RrS4ya4QTHBKT7XxSaCfS1JxoACWZ750lzje0sZpejBY_6tu0AzK1pAshzJ4m
