name: build checklist-apps

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Create .env file
        run: |
          echo PORT=${{ secrets.PORT }} >> .env
          echo GIN_MODE=${{ secrets.GIN_MODE }} >> .env
          echo SMTP_PASSWORD=${{ secrets.SMTP_PASSWORD }} >> .env
          echo SMTP_PORT=${{ secrets.SMTP_PORT }} >> .env
          echo SMTP_HOST=${{ secrets.SMTP_HOST }} >> .env
          echo SMTP_FROM=${{ secrets.SMTP_FROM }} >> .env
          echo MONGO_URL=${{ secrets.MONGO_URL }} >> .env
          echo DISCORD_WEBHOOK_URL=${{ secrets.DISCORD_WEBHOOK_URL }} >> .env

      - name: Cache Go modules
        uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Set up Go
        uses: actions/setup-go@v2

      - name: Build Code
        run: go build -v ./...

      - name: Run Tests
        run: go test -v ./...

      - name: Install GolangCI-Lint
        run: go get github.com/golangci/golangci-lint/cmd/golangci-lint@v1.42.0

      - name: Run GolangCI-Lint
        run: golangci-lint run ./... || true

      - name: Install Hadolint
        run: wget https://github.com/hadolint/hadolint/releases/download/v2.7.0/hadolint-Linux-x86_64 -O hadolint && chmod +x hadolint

      - name: Lint Dockerfile
        run: ./hadolint Dockerfile || true

      - name: Build Docker Image
        run: docker build --build-arg .env=.env -t checklist-apps .
